In [2]:
%matplotlib widget
from bmcs_shell.api import WBTessellation4P, WBShellAnalysis, MATS2DElastic
import numpy as np

In [2]:
tmodel = MATS2DElastic(E=28000, nu=0.2)
n_phi_plus=1
n_x_plus=1
wbm = WBShellAnalysis(h=10, tmodel=tmodel)

In [3]:
data = dict(gamma=0.33, a=500, a_high=3000, b=900, b_high=3000, c=400, c_high=2000,
            n_phi_plus=n_phi_plus, n_x_plus=n_x_plus, show_nodes=False)
wbm.geo.trait_set(**data)

In [ ]:
wbm.xdomain.mesh.direct_mesh = False
wbm.xdomain.mesh.subdivision = 2

In [17]:
mesh = wbm.xdomain.mesh.mesh
mesh

<meshio mesh object>
  Number of points: 21
  Number of cells:
    line: 32
    triangle: 20
    vertex: 7

In [4]:
wbm.interact()

analysis: setup_plot
analysis: U_I
analysis: update_plot
analysis: U_I


C:\Users\hspartali\Anaconda3\envs\bmcs_env\lib\site-packages\traittypes\traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


Point, facets
You need the average of facets normal for each point

In [52]:
X_Id = wbm.xdomain.mesh.X_Id
X_Id

array([[   0.        ,    0.        ,    0.        ],
       [ 500.        ,  826.05615234,  357.25585938],
       [-500.        ,  826.05615234,  357.25585938],
       [ 500.        , -826.05615234,  357.25585938],
       [-500.        , -826.05615234,  357.25585938],
       [ 129.61721802,    0.        ,  378.41699219],
       [-129.61721802,    0.        ,  378.41699219]])

In [30]:
wbm.xdomain.mesh.I_Fi

array([[0, 1, 2],
       [0, 3, 4],
       [0, 1, 5],
       [0, 5, 3],
       [0, 2, 6],
       [0, 6, 4]])

In [40]:
np.arange(I_Fi.shape[0])[:, np.newaxis].shape

(6, 1)

In [42]:
F_indices = np.arange(I_Fi.shape[0])[:, np.newaxis]
np.hstack((I_Fi[:, :2], F_indices))

array([[0, 1, 0],
       [0, 3, 1],
       [0, 1, 2],
       [0, 5, 3],
       [0, 2, 4],
       [0, 6, 5]])

In [49]:
I_Li[:, :2]

array([[0, 1],
       [0, 3],
       [0, 1],
       [0, 5],
       [0, 2],
       [0, 6],
       [1, 2],
       [3, 4],
       [1, 5],
       [5, 3],
       [2, 6],
       [6, 4]])

In [50]:
I_Li

array([[0, 1, 0],
       [0, 3, 1],
       [0, 1, 2],
       [0, 5, 3],
       [0, 2, 4],
       [0, 6, 5],
       [1, 2, 0],
       [3, 4, 1],
       [1, 5, 2],
       [5, 3, 3],
       [2, 6, 4],
       [6, 4, 5]])

In [53]:
X_Id[I_Li]

array([[[   0.        ,    0.        ,    0.        ],
        [ 500.        ,  826.05615234,  357.25585938],
        [   0.        ,    0.        ,    0.        ]],

       [[   0.        ,    0.        ,    0.        ],
        [ 500.        , -826.05615234,  357.25585938],
        [ 500.        ,  826.05615234,  357.25585938]],

       [[   0.        ,    0.        ,    0.        ],
        [ 500.        ,  826.05615234,  357.25585938],
        [-500.        ,  826.05615234,  357.25585938]],

       [[   0.        ,    0.        ,    0.        ],
        [ 129.61721802,    0.        ,  378.41699219],
        [ 500.        , -826.05615234,  357.25585938]],

       [[   0.        ,    0.        ,    0.        ],
        [-500.        ,  826.05615234,  357.25585938],
        [-500.        , -826.05615234,  357.25585938]],

       [[   0.        ,    0.        ,    0.        ],
        [-129.61721802,    0.        ,  378.41699219],
        [ 129.61721802,    0.        ,  378.41699219]],

In [79]:
# Unique lines
I_Li = np.vstack(((I_Fi[:, (0, 1)]), (I_Fi[:, (0, 2)]), (I_Fi[:, (1, 2)])))
I_Li = np.sort(I_Li, axis=1)
I_Li = np.unique(I_Li, axis=0)
I_Li

array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 5],
       [0, 6],
       [1, 2],
       [1, 5],
       [2, 6],
       [3, 4],
       [3, 5],
       [4, 6]])

In [120]:
I_Fi_sorted[:, :2] == I_Li

C:\Users\spart\AppData\Local\Temp\ipykernel_3084\1041612765.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  I_Fi_sorted[:, :2] == I_Li


False

In [135]:
a = np.where(np.sum((I_Fi_sorted[:, 1:] == I_Li[0])*1, axis=1) == 2)[0]
a

array([], dtype=int64)

In [170]:
np.sum((I_Fi_sorted[:, 1:] == I_Li[:, np.newaxis])*1, axis=2)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [2, 0, 1, 0, 0, 0],
       [1, 0, 2, 1, 0, 0],
       [0, 0, 0, 0, 2, 1],
       [0, 2, 0, 1, 0, 0],
       [0, 1, 1, 2, 0, 0],
       [0, 0, 0, 0, 1, 2]])

In [204]:
arr = np.sum((I_Fi_sorted[:, 1:] == I_Li[:, np.newaxis])*1, axis=2)
arr = np.where(arr == 2)
np.vstack((arr[0], arr[1])).T

array([[ 5,  0],
       [ 6,  2],
       [ 7,  4],
       [ 8,  1],
       [ 9,  3],
       [10,  5]], dtype=int64)

In [205]:
I_Fi_sorted[:, :2]

array([[0, 1],
       [0, 3],
       [0, 1],
       [0, 3],
       [0, 2],
       [0, 4]])

In [198]:
arr = np.sum((I_Fi_sorted[:, :2] == I_Li[:, np.newaxis])*1, axis=2)
arr = np.where(arr == 2)
np.vstack((arr[0], arr[1])).T

array([[0, 0],
       [0, 2],
       [1, 4],
       [2, 1],
       [2, 3]], dtype=int64)

In [169]:
np.sum((I_Fi_sorted[:, :2] == I_Li[:, np.newaxis])*1, axis=2)

array([[2, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1],
       [1, 2, 1, 2, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [165]:
b = np.where(np.sum((I_Fi_sorted[:, :2] == I_Li[:, np.newaxis])*1, axis=2) == 2)
b

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))

In [78]:
I_Fi_sorted = np.sort(I_Fi, axis=1)
I_Fi_sorted

array([[0, 1, 2],
       [0, 3, 4],
       [0, 1, 5],
       [0, 3, 5],
       [0, 2, 6],
       [0, 4, 6]])

In [70]:
I_Fi

array([[0, 1, 2],
       [0, 3, 4],
       [0, 1, 5],
       [0, 5, 3],
       [0, 2, 6],
       [0, 6, 4]])

In [51]:
I_Fi = wbm.xdomain.mesh.I_Fi
F_indices = np.arange(I_Fi.shape[0])[:, np.newaxis]
I_Li = np.vstack((np.hstack((np.sort(I_Fi[:, :2]), F_indices)), np.hstack((np.sort(I_Fi[:, 1:]), F_indices))))
# I_Li = np.vstack((np.hstack((I_Fi[:, :2], F_indices)), np.hstack((I_Fi[:, 1:], F_indices))))
I_Li

array([[0, 1, 0],
       [0, 3, 1],
       [0, 1, 2],
       [0, 5, 3],
       [0, 2, 4],
       [0, 6, 5],
       [1, 2, 0],
       [3, 4, 1],
       [1, 5, 2],
       [3, 5, 3],
       [2, 6, 4],
       [4, 6, 5]])

In [48]:
np.sort(I_Li, axis=0)

array([[0, 1, 0],
       [0, 1, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 3, 2],
       [0, 3, 2],
       [1, 4, 3],
       [1, 4, 3],
       [2, 5, 4],
       [3, 5, 4],
       [5, 6, 5],
       [6, 6, 5]])

In [22]:
wbm.xdomain.norm_F_normals

array([[ 0.        , -0.39695083,  0.91783988],
       [ 0.        ,  0.39695083,  0.91783988],
       [-0.86831576,  0.39694994,  0.29741971],
       [-0.86831576, -0.39694994,  0.29741971],
       [ 0.86831576,  0.39694994,  0.29741971],
       [ 0.86831576, -0.39694994,  0.29741971]])

In [ ]:
xmodel = wbm.fe_domain[0].xmodel
xmodel.mesh.I_CDij

In [ ]:
_, idx_remap = xmodel.mesh.unique_node_map

In [ ]:
idx_remap[xmodel.mesh.I_CDij]

In [ ]:
idx_remap[xmodel.mesh.I_CDij[(0, -1),:,(0, -1),:].flatten()]

In [ ]:
xmodel

In [ ]:
wbm.interact()

In [ ]:
import numpy as np
alpha_range = np.linspace(0.5, 1.3, 10)
a_range = np.linspace(300,500,10)

In [ ]:
tmodel = MATS2DElastic(E=28000, nu=0.2)
import numpy as np
U_grid = []
sig_grid = []
for alpha in alpha_range:
    U_list = []
    sig_list = []
    for a in a_range:
        wbm = WBShellAnalysis(F=-20000, h=10, tmodel=tmodel)
        data = dict(alpha=alpha, a=a, a_high=2000, b=1250, b_high=2000, c=400, c_high=2000,
                    n_phi_plus=n_phi_plus, n_x_plus=n_x_plus)
        wbm.wb_mesh.trait_set(**data)
        max_U = wbm.get_max_vals()
        
        U1 = wbm.hist.U_t[-1]
        eps1 = wbm.fe_domain[0].xmodel.map_U_to_field(U1)
        sig1, _ = wbm.fe_domain[0].tmodel.get_corr_pred(eps1,1)
        sig_x, sig_y, tau = sig1.T
        sig_ab = np.einsum('ab...->...ab', np.array([[sig_x, tau], [tau, sig_y]], dtype=np.float_))
        sig_val, sig_dir = np.linalg.eig(sig_ab)
        sig_list.append([np.min(sig_val), np.max(sig_val)])

        print(alpha, a, max_U)
        U_list.append(max_U)
    U_grid.append(U_list)
    sig_grid.append(sig_list)

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
fig = plt.figure()
ax = fig.gca(projection='3d')
X, Y = np.meshgrid(alpha_range, a_range)
Z = np.array(U_grid)
surf = ax.plot_surface(X, Y, Z, 
                       color='green',
                       #linewidth=0, antialiased=False)
                    alpha=.0, linewidth=5,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
Z = np.array(sig_grid)[:,:,1]
surf = ax.plot_surface(X, Y, Z,color='red', 
                       #cmap=cm.copper,
                    alpha=.3, linewidth=3,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
Z = -np.array(sig_grid)[:,:,0]
surf = ax.plot_surface(X, Y, Z,color='blue', 
                       #cmap=cm.copper,
                    alpha=.6, linewidth=3,
                       #cmap=cm.gist_earth,antialiased=False, 
                shade=False,rstride=1, cstride=1)
ax.set_xlabel(r'$\alpha~[\mathrm{rad}]$')
ax.set_ylabel(r'$a~[\mathrm{mm}]$')
ax.set_zlabel(r'max compression [MPa]')


In [ ]:
i_alpha, i_a = 0, -1
wbm = WBShellAnalysis(F=-1000, tmodel=tmodel)
print('alpha', alpha_range[i_alpha],'a', a_range[i_a] )
data = dict(alpha=alpha_range[i_alpha], 
            a=a_range[i_a], a_high=2000, b=1250, b_high=2000, c=400, c_high=2000,
            n_phi_plus=n_phi_plus, n_x_plus=n_x_plus)
wbm.wb_mesh.trait_set(**data)
wbm.wb_mesh.interact()

In [ ]:
15000 / 39000 